services:
  reporte-services:
    build: .
    container_name: reporte-services
    restart: unless-stopped
    ports:
      - "5007:5007"
    environment:
      # URL apuntando a tu MySQL en Windows
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/reporte?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: reporte
      SPRING_DATASOURCE_PASSWORD: system
      # Si tu microservicio necesita comunicarse con otros, añade aquí las variables de entorno
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - red-microservicios
networks:
  red-microservicios:
    external: true